In [4]:
import numpy as np

A = [[2, -1], [0, 3]]
B = [[1, 4], [-2, 5]]
c = 2
d = 3


compute_A = np.array([[2, -1], [0, 3]])
compute_B = np.array([[1, 4], [-2, 5]])
print(f"This is matrix A:\n", compute_A)
print(" ")
print(f"This is matrix B:\n", compute_B)

This is matrix A:
 [[ 2 -1]
 [ 0  3]]
 
This is matrix B:
 [[ 1  4]
 [-2  5]]


In [8]:
cA = c * compute_A
dB = d * compute_B
cdA = (c +d) * compute_A

print("cA:\n",cA)
print(" ")
print("dB:\n",dB)
print(" ")
print("(c + d)A:\n",cdA)

cA:
 [[ 4 -2]
 [ 0  6]]
 
dB:
 [[ 3 12]
 [-6 15]]
 
(c + d)A:
 [[10 -5]
 [ 0 15]]


b. Using results gotten, verify the scalar multiplication properties

In [ ]:
# d = 3
# compute_A has stored the value of A as a variable, so I'm just gonna use the variable below.

sc_mult = cA + (d * compute_A)
print("The scalar multiplication of the above is:\n",sc_mult)

The scalar multiplication of the above is:
 [[10 -5]
 [ 0 15]]


c. Transpose of `A` and `B`

In [12]:
# Values of A and B has been stored in compute_A and compute_B respectively.

A_transpose = compute_A.T
B_transpose = compute_B.T

print("The transpose of A is:\n", A_transpose)
print("")
print("The transpose of B is:\n", B_transpose)

The transpose of A is:
 [[ 2  0]
 [-1  3]]

The transpose of B is:
 [[ 1 -2]
 [ 4  5]]


d.  Check if _`(A)`_ and _`(B)`_ are invertible by computing their determinants. If they are invertible, find: $A^{-1}$ and $B^{-1}$