In [1]:
import numpy as np



In [ ]:
# 3.1 Representing Data as a Matrix

student_scores = np.array([[80, 70, 90],
                          [60, 85, 75],
                          [95, 88, 92],
                          [70, 60, 65]])
student_scores

array([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])

In [ ]:
# 3.2 Total Scores per Student
row_of_sum1 = np.sum(student_scores, axis=1)
for i, total in enumerate(row_of_sum1, 1):
    print(f"The total score for student{i} is {total}")

The total score for student1 is 240
The total score for student2 is 220
The total score for student3 is 275
The total score for student4 is 195


In [ ]:
#3.3 Applying Weights (Scalar Multiplication)
weighted_maths = np.array([2, 1, 1])
weighted_maths = student_scores * weighted_maths
print("Since maths is twice as important as others. Weighted scores is:\n", weighted_maths)

new_score = weighted_maths
print(" ")

row_of_sum2 = np.sum(weighted_maths, axis=1)

for i, total in enumerate(row_of_sum2, 1):
    print(f"Total score for student{i} is {total}")



Since maths is twice as important as others. Weighted scores is:
 [[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]
 
Total score for student1 is 320
Total score for student2 is 280
Total score for student3 is 370
Total score for student4 is 265


In [ ]:
# 3.4 Average score per students (Matrix Operations)

subjects = ["Maths", "English", "Science"]
average_subject = np.mean(new_score, axis=0)

for subject, avg in zip(subjects, average_subject):
    print(f"Average of {subjects} is {avg}")



Average of ['Maths', 'English', 'Science'] is 152.5
Average of ['Maths', 'English', 'Science'] is 75.75
Average of ['Maths', 'English', 'Science'] is 80.5


In [ ]:
# 3.5 Final Grades using Matrix Multiplication

grades = np.array([0.5, 0.3, 0.2])
final_grade = np.matmul(new_score, grades)


for i, grade in enumerate(final_grade, 1):
    print(f"The final grade for student{i} is {grade}")
    


The final grade for student1 is 119.0
The final grade for student2 is 100.5
The final grade for student3 is 139.8
The final grade for student4 is 101.0


In [39]:
# 3.6 Comparing students (vector substraction)

student1 = new_score[0]
student2 = new_score[1]

sum_of_student1 = np.sum(new_score[0])
sum_of_student2 = np.sum(new_score[1])

comparing_student = sum_of_student1 - sum_of_student2

if comparing_student > 0:
    print("Student1 performed better")
elif comparing_student < 0:
    print("Student2 performed better")
else:
    print("Both student tie")


Student1 performed better
