# Question 1
Create a 6x6 Numpy array with random integers between 1 and 50. Display the array.

In [102]:
import numpy as np
arr6d = np.random.randint(1, 50, size=(6, 6))
print(arr6d)

[[30 41 42 39  9 42]
 [10  4 29 23 14  7]
 [42 23 35 12 12 18]
 [19 41 13 49 36  2]
 [45  6 32 14  6 27]
 [22 12 26 11 35 20]]


# Question 2
Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.

In [ ]:
# Get first two rows
first_two_rows = arr6d[:2]
print(first_two_rows)

# Get last 3 columns
print(" ")
last_three_col = arr6d[0:, -3:]
print(f"The last three columns are: {last_three_col}")

# Print all even numbers in array
print(" ")
even_num = arr6d[arr6d % 2 == 0 ]
print(f"The even numbers are: {even_num}")


# Question 3

Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

In [104]:
# Reshape array into 3D
reshaped_array = arr6d.reshape(3,2,6)
print(reshaped_array)


# Flatten array
flattened_array = reshaped_array.flatten()
print(flattened_array)

[[[30 41 42 39  9 42]
  [10  4 29 23 14  7]]

 [[42 23 35 12 12 18]
  [19 41 13 49 36  2]]

 [[45  6 32 14  6 27]
  [22 12 26 11 35 20]]]
[30 41 42 39  9 42 10  4 29 23 14  7 42 23 35 12 12 18 19 41 13 49 36  2
 45  6 32 14  6 27 22 12 26 11 35 20]


# Question 4

Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [128]:
import numpy as np

# Generate 4x4 identity matrix
identity_matrix = np.eye(4)
print(identity_matrix)

# Replace diagnoal with numbers 10 to 40 with step 10.
print(" ")
replace_diagonal = np.diag(np.arange(10, 50, 10))
print(replace_diagonal)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


# Question 5
Perform matrix multiplication between: A 3x4 matrix of random integers (1-10). A 4x3 matrix of random integers (1 - 10). A 4x3 matrix of random integers (1-10)

In [ ]:
random_num1 = np.random.randint(1, 10, size=(3,4))
random_num2 = np.random.randint(1, 10, size=(4,3))
print(random_num1)
print(random_num2)
print(" ")
multiply_random = np.matmul(random_num1, random_num2)
print("Matrix 1 is multiplied by 2:\n", multiply_random)

[[2 9 8 3]
 [1 2 5 8]
 [4 9 6 9]]
[[4 1 2]
 [4 8 6]
 [7 6 7]
 [6 3 5]]
 
Matrix 1 is multiplied by 2
 [[118 131 129]
 [ 95  71  89]
 [148 139 149]]


# Question 6
Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1